### ISSUE TITLE
Typescript error!

### ISSUE THREAD

**Issue by ddzy** [frontend-collective/react-image-lightbox#153]
# Reporting a Bug?

**Hi, guys!
When I introduced it in typescript, an error occurred.**
![az0ojp4 ij5 he m63ax 02](https://user-images.githubusercontent.com/33921398/48998143-86db4580-f18d-11e8-8f2e-3605dfd88843.png)

**Comment by dacevedo12** [comment]
are you installing it from npm? the latest published version is 5.0.0 which didn't include the types definition file added a month later.

btw, @mmarkelov do you have any idea when will be the next release to npm? im having this same issue. 

Also, installing from git in package.json is not an option because this repo doesnt appear to be properly configured to allow it.

**Comment by mmarkelov** [comment]
@dacevedo12 I don't have any ideas - I also wait a new release

**Comment by dacevedo12** [comment]
@ddzy 5.1.0 was released 19 days ago containing types definition. This issue should be closed.
