### ISSUE TITLE
Pinch-to-Zoom broken on iOS 11/12

### ISSUE THREAD

**Issue by CaptainLexington** [frontend-collective/react-image-lightbox#154]
Pinch to Zoom is broken on iOS11/12 devices. When you pinch to zoom, instead of scaling the image in place (like on my Chromebook, Pixel 2, or on iOS 10), it scales the entire page, and often the browser window itself. This can be reproduced with the hosted demo, on an iOS device running iOS 11/12 or in an emulator.

**Comment by eruby94** [comment]
I can confirm that this happens for me as well. I have experienced this on iPad Pros, using iOS 11.3.1.

**Comment by RickeyWard** [comment]
I have this issue also, I'm sure it has to do with safari ignoring user-scalable but I don't know a fix.

**Comment by johndigital** [comment]
Just wanted to drop in here and mention that I was seeing weird and broken looking pinch/zoom behavior on iOS. I changed my viewport meta tag to disable native zooming and it solved the problem for me completely. The meta tag on my site now looks like this:
```html
<meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
```

This solution may not address what OP was referring to when the issue was opened originally, but since I ended up here in search of a solution I figured others may as well.
