### ISSUE TITLE
Does it work with React 18?

### ISSUE THREAD

**Issue by dev-medclans** [frontend-collective/react-image-lightbox#657]
I tried to use this in my project which has React 18.2
I am getting 'Couldn't resolve dependency' error.

How do I make this library work with React 18?

**Comment by Fidia-e** [comment]
https://www.npmjs.com/package/react-18-image-lightbox

**Comment by larinius** [comment]
I tried version from this repository - it works with React 18 and Nextjs. 

This is only image swiper I have found which works just out of the box with Next. Others have issues related to image loading.

**Comment by donaldboulton** [comment]
https://www.npmjs.com/package/react-18-image-lightbox 

Loads so much Faster using react 18.  Never see the Loader image now. The package owner needs to change the import to

`import Lightbox from 'react-18-image-lightbox'`

Since I use tailwind I added the style.css to my Gallery component folder and used.

`import './style.css'`
